const fs = require('fs');
const path = require('path');

const partsDir = path.join(__dirname, '..', 'prisma_db_schema');
const outFile = path.join(__dirname, '..', 'prisma', 'schema.prisma');

const files = fs.readdirSync(partsDir)
  .filter(f => f.endsWith('.prisma'))
  .sort();

const header = `// AUTO-GENERATED by scripts/concat-prisma.js
// Do not edit this file directly. Edit files under prisma/parts and run the build script.
`;

const content = files.map(f => {
  const p = path.join(partsDir, f);
  return fs.readFileSync(p, 'utf8');
}).join('\n\n');

fs.writeFileSync(outFile, header + '\n' + content, 'utf8');
console.log('Wrote', outFile);
